CREATE TABLE bookings(
    booking_number CHAR(10) NOT NULL,
    number_guests INT NOT NULL,
    adults INT,
    kids INT,
    babies INT,
    pets INT,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    number_of_nights INT NOT NULL,
    booking_date DATE NOT NULL,
    ppn_avg_discount FLOAT(24) NOT NULL,
    cleaning_fee FLOAT(24),
    service_fee FLOAT(24) NOT NULL,
    total_paid FLOAT(24) NOT NULL,
    total_nights_no_discount FLOAT(24) NOT NULL,
    total_discount FLOAT(24),
    service_fee_renter FLOAT(24) NOT NULL,
    total_received FLOAT(24) NOT NULL,
    cancelled BOOL,
    date_of_cancel DATE,
    guest INT,
    PRIMARY KEY(booking_number),
    FOREIGN KEY (guest) REFERENCES guests(person_ID)
);