CREATE TABLE bookings(
    booking_number CHAR(10) NOT NULL,
    number_guests INT ,
    adults INT,
    kids INT,
    babies INT,
    pets INT,
    check_in DATE ,
    check_out DATE ,
    number_of_nights INT ,
    booking_date DATE ,
    avg_ppn_incl_discount FLOAT(24) ,
    cleaning_fee FLOAT(24),
    service_fee_guest FLOAT(24) ,
    total_paid FLOAT(24) ,
    total_nights_excl_discount TINYTEXT ,
    total_discount FLOAT(24),
    service_fee_landlord FLOAT(24) ,
    total_received FLOAT(24) ,
    cancelled BOOL,
    date_of_cancel DATE,
    bed_config TINYTEXT,
    guest INT,
    PRIMARY KEY(booking_number),
    FOREIGN KEY (guest) REFERENCES guests(person_ID)
);