CREATE TABLE guests (
    person_ID INT NOT NULL AUTO_INCREMENT,
    guest_given_name TINYTEXT ,
    guest_surname TINYTEXT ,
    rating DEC(2,1),
    cleanliness DEC(2,1),
    houserules DEC(2,1),
    communication DEC(2,1),
    number_of_travels INT,
    number_of_ratings INT,
    airbnb_member_since YEAR,
    country_of_residence TINYTEXT,
    city_of_residence TINYTEXT,
    nationality TINYTEXT,
    job TINYTEXT,
    email TINYTEXT,
    age TINYTEXT,
    phone TINYTEXT,
    comments VARCHAR (3000),
    candidate_lastminute BOOL,
    bed_config TINYTEXT,
    PRIMARY KEY (person_ID)
);